#ifndef MAPS_PARSER_H
#define MAPS_PARSER_H

#include <tinyxml2.h>

#include <map>
#include <string>

#include "Maps/GameMap.h"
#include "Maps/TitleLayer.h"

/**
 * Map Parser
 *
 * A parser for maps generated by the "Tiled" editor
 *
 * @see https://www.mapeditor.org/
 *
 * @author Alin Eugen Deac <aedart@gmail.com>
 */
class Parser
{
    public:
        /**
         * Prevent copy constructor
         */
        Parser(const Parser&) = delete;

        /**
         * Prevent assignment
         *
         * @return
         */
        Parser& operator=(const Parser&) = delete;

        /**
         * Get singleton instance of this map parser
         *
         * @return
         */
        static Parser& getInstance();

        /**
         * Destroy the map parser instance
         */
        static void destroy();

        /**
         * Destructor
         */
        virtual ~Parser();

    protected:

        /**
         * Default constructor
         */
        Parser();

    private:

        /**
         * Singleton instance
         */
        inline static Parser* instance = nullptr;
};

#endif  // MAPS_PARSER_H
